#FORMAT SPECIFIERS : {VALUE : FLAGS}
#:(NUMBER)f ALLOCATES A SET NUMBER OF DECIMAL PLACES TO BE ROUNDED OFF TO
#:(NUMBER) ALLOCATES THAT MANY SPACES FOR THE NUMBER
#:0(NUMBER) ZERO PADS THAT MANY SPACES
#:< LEFT JUSTIFY
#:> RIGHT JUSTIFY
#:^ CENTER ALIGN
#:+ USE A PLUS SIGN TO INDICATE POSITIVE VALUE
#:= PLACE SIGN TO THE LEFTMOST POSITION
#:  INSERT A SPACE BETWEEN POSITIVE NUMBERS
#:, ADD COMMA SEPARATORS IN NUMBERS
import math
E=math.pi**2
print(f"THE VALUE IS {E:.4f}")
print(f"THE VALUE IS {E:10}")
print(f"THE VALUE IS {E:+}")
print(f"THE VALUE IS {E:-}")
print(f"THE VALUE IS {E:=}")
print(f"THE VALUE IS {E:<}")
print(f"THE VALUE IS {E:>}")