#input() :- A FUNCTION THAT PROMPTS THE USER TO ENTER A DATA
#input() TAKES IN DATA AS STRINGS, HENCE THEY NEED TO BE TYPECAST INTO THE DESIRED DATA TYPE
NAME=input("WHAT IS YOUR NAME?")
AGE=int(input("WHAT IS YOUR AGE?"))
AGE+=1
print(f"HELLO {NAME}")
print(f"HAPPY {AGE}TH BIRTHDAY")
#USE CASE
print(f"ENTER THE BREADTH")
len=int(input("ENTER YOUR LENGTH HERE"))
print(f"ENTER THE LENGTH")
bre=int(input("ENTER YOUR BREADTH HERE"))
area=len*bre
print(f"THE NET AREA IS {area}")
