#WHILE LOOP : USED TO ITERATE STATEMENTS UNTIL A CONDITION REMAINS TRUE
#FOR LOOP : USED TO ITERATE A SET NUMBER OF TIMES
import math
PRINCIPLE=0
RATE=0
TIME=0
while PRINCIPLE<=0:
    PRINCIPLE = float(input("ENTER THE PRINCIPAL"))
    if PRINCIPLE<0 :print("PRINCIPLE CANNOT BE ZERO")
while RATE<=0:
    RATE = float(input("ENTER THE RATE"))
    if RATE<0 :print("RATE CANNOT BE ZERO")
while TIME<=0:
    TIME = float(input("ENTER THE TIME"))
    if TIME<0 :print("TIME CANNOT BE ZERO")
TOTAL=PRINCIPLE*pow(1+RATE/100,TIME)
print(f"THE TOTAL AMOUNT TO PAYBACK AFTER {TIME} YEARS IS {TOTAL:.2f}")
#FOR LOOPS
for x in reversed(range(1,11)):
    print(x)
print("HAPPY NEW YEAR")